//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIREWALL
    {
        public string DATE { get; set; }
        public string TIME { get; set; }
        public string ACTION { get; set; }
        public string PROTOCOL { get; set; }
        public string SRC_IP { get; set; }
        public string DST_IP { get; set; }
        public string SRC_PORT { get; set; }
        public string DST_PORT { get; set; }
        public string SIZE { get; set; }
        public string PATH { get; set; }
        public long ID { get; set; }
    }
}
