//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KASPERSKY
    {
        public string NUMBER { get; set; }
        public string MONTH { get; set; }
        public string CHISLO { get; set; }
        public string TIME { get; set; }
        public string INFO { get; set; }
        public Nullable<double> AVP { get; set; }
        public string CODE { get; set; }
        public long ID { get; set; }
    }
}
